version: '3'

services: 
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql    
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=docker
    networks: 
      - nodenetwork  

networks: 
  nodenetwork:
    driver: bridge